#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>   // required for fork()

// program to sum all elemnts of array
// left half to be summed by child and right half to be summed by parent
// child will write the sum to the parent and parent adds this to its own sum and display

int main()
{
    int array[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    int sum = 0;
    int start, end;
    int fd[2]; // array to hold read and write ends of pipe
    pipe(fd);

    int id = fork();
    if (id == 0)
    {
        start = 0;
        end = 5;
        close(fd[0]);  // read end not required in chil
    }
    else
    {
        start = 5; 
        end = 10;
        close(fd[1]); // write end not required in parent
    }

    for (int i = start; i < end; i++)
    {
        sum = sum + array[i];
    }

    if (id == 0)
    {
        printf("Sum generated by child: %d\n",sum);
        write(fd[1], &sum, sizeof(int));
        close(fd[1]); // write end closed in child
    }
    else
    {
        printf("Sum generated by parent: %d\n",sum);
        int childsum;
        read(fd[0],&childsum, sizeof(int));
        close(fd[0]);  // read end closed in parent

        sum = sum + childsum;
        printf("Sum of the whole array: %d\n",sum);
    }

    return 0;
}